# This file was generated by GoReleaser. DO NOT EDIT.
cask "yeet" do
  name "yeet"
  desc "Automate releases based on conventional commits"
  homepage "https://github.com/monkescience/yeet"
  version "0.4.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yeet"

  on_macos do
    on_intel do
      url "https://github.com/monkescience/yeet/releases/download/v#{version}/yeet_darwin_amd64.tar.gz"
      sha256 "ffd205c66866e2ce208cdd28103034b5af70cf281543851eed261947448e0347"
    end
    on_arm do
      url "https://github.com/monkescience/yeet/releases/download/v#{version}/yeet_darwin_arm64.tar.gz"
      sha256 "62b6111e69cc1948647e62ca49909a71d089e41fe2541253d61b34343f719b7c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/monkescience/yeet/releases/download/v#{version}/yeet_linux_amd64.tar.gz"
      sha256 "ad0d8d66ae081ce35879098b05f6b8a865a68181f06611fbd8b6066616c20e4c"
    end
    on_arm do
      url "https://github.com/monkescience/yeet/releases/download/v#{version}/yeet_linux_arm64.tar.gz"
      sha256 "d681ba9aea7513fe7b53f5592619c7b3fde17d99f53a5f157423d331245002f5"
    end
  end

  # No zap stanza required
end
