# This file was generated by GoReleaser. DO NOT EDIT.
cask "yeet" do
  version "0.6.1"

  on_macos do
    on_intel do
      url "https://github.com/monkescience/yeet/releases/download/v#{version}/yeet_darwin_amd64.tar.gz"
      sha256 "a43eec4eec9aed957732ab4aae3a89d6cda618a643b10c858f22b6af43acf603"
    end
    on_arm do
      url "https://github.com/monkescience/yeet/releases/download/v#{version}/yeet_darwin_arm64.tar.gz"
      sha256 "1ce5f0695ca657fafb7c9e696eff6771f917c86a2f2ef937a19e7e938fe7b70b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/monkescience/yeet/releases/download/v#{version}/yeet_linux_amd64.tar.gz"
      sha256 "d58f05ee9da4903481c01366160c827b8088a2b798e3b96955807ad80b65ebc2"
    end
    on_arm do
      url "https://github.com/monkescience/yeet/releases/download/v#{version}/yeet_linux_arm64.tar.gz"
      sha256 "4850fb7b31712f25e7b142e47f87674319bd4616399aa5b8a5e71cdcdb9086fb"
    end
  end

  name "yeet"
  desc "Automate releases based on conventional commits"
  homepage "https://github.com/monkescience/yeet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yeet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yeet"]
    end
  end

  # No zap stanza required

end
