# This file was generated by GoReleaser. DO NOT EDIT.
cask "yeet" do
  version "0.13.8"

  on_macos do
    on_intel do
      sha256 "6a86a4ca2a128db630525427df95b636de7886711664f28089c37fc33ef38f81"
      url "https://github.com/monkescience/yeet/releases/download/v#{version}/yeet_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fadc366efffadba4dd6d4e440feddf22ee71548af798bdf9a9952a21140f9c9b"
      url "https://github.com/monkescience/yeet/releases/download/v#{version}/yeet_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "66b48b77f97f8eff654bbcd92596952a420c462891c97e52cd26205fd8a5c15c"
      url "https://github.com/monkescience/yeet/releases/download/v#{version}/yeet_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a1591d472cd13b12343d055d2bd5bafd43cebf8ffd9654f69ab6b6f7a3bba20d"
      url "https://github.com/monkescience/yeet/releases/download/v#{version}/yeet_linux_arm64.tar.gz"
    end
  end

  name "yeet"
  desc "Automate releases based on conventional commits"
  homepage "https://github.com/monkescience/yeet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yeet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yeet"]
    end
  end

  # No zap stanza required

end
