name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  audit:
    name: cask-audit
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Tap checked out repository
        run: brew tap --custom-remote monkescience/tap "$GITHUB_WORKSPACE"

      - name: Audit tap casks
        run: brew audit --strict --online --display-filename --os all --arch all --cask --git --tap monkescience/tap
